### ISSUE TITLE
Enivornment variables don't work on linux

### ISSUE THREAD

**Issue by sage-t** [SpectraLogic/ds3_script#34]

**Comment by gtrossell** [comment]
Hello Sage, 

You have a hard coded port :80 in your environment, which isn't getting over written by the environment variables. 

I am using Linux, I can set my environment variables fairly simply by running;
source setup.sh

This then sets my environment up for the whole ssh session, provided I dont exit out of the ssh session into my Ubuntu host.

However if part of that setup file I define my host as xxx.xxx.xxx:80 

When I try and do anything within groovy it responses with host xxx.xxx.xxx.:80:80 which means you have a hard coded :80 in your program.

**Comment by sage-t** [comment]
Hi George, I looked into your issue, but can't seem to replicate it. There is no hard coded :80 in the project either. Could you log your error and upload it here? You can debug and log by running `bpsh -d -l .` and trying your code out. This will make a file called `spectra.log` in the working directory.

**Comment by gtrossell** [comment]
When I remove the :80 from my environment variables, I dont get a stack trace.

In the logs, ignore the failed upload ;) 

[spectra1.log](https://github.com/SpectraLogic/ds3_script/files/1948769/spectra1.log)

Here is my setup file that works;

cat setup.sh 
export DS3_ACCESS_KEY=Z2Vvcmdl
export DS3_SECRET_KEY=xxxxxxxxxx
export DS3_ENDPOINT=10.210.3.110

 This is what the setup file looks like when it fails, but conforms to the JavaCLI requirements.

cat setup.sh 
export DS3_ACCESS_KEY=Z2Vvcmdl
export DS3_SECRET_KEY=xxxxxxxxxxxx
export DS3_ENDPOINT=10.210.3.110:80

I add this to my ds3 credentials to my terminal session by running the following command before launching then ds3_script.

`source setup.sh`

**Comment by rpmoore** [comment]
@gtrossell what does your script look like?

**Comment by rpmoore** [comment]
Nevermind, I saw it in the log file.

**Comment by rpmoore** [comment]
@gtrossell what system are you running this against?

**Comment by gtrossell** [comment]
@rpmoore 

Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

**Comment by rpmoore** [comment]
@gtrossell My mistake, I meant the Black Pearl, and it's version

**Comment by gtrossell** [comment]
@rpmoore it's a real 4U 10 disk BlackPearl in the UK lab

BlackPearl code 4.1.1

**Comment by sage-t** [comment]
DS3 SDK version was a bit old. After updating that it fixed the issue.
