### ISSUE TITLE
Can not getBulk a root folder to retrieve its full contents in one command 

### ISSUE THREAD

**Issue by gtrossell** [SpectraLogic/ds3_script#35]
Doing an getBulk you can not specify the root directory on its own and have it collect everything within that directory.

spectra> bucket.getBulk(['dir1'], "./")
===> Status Code (NotFound) Message: NotFound[404]: Objects do not exist: [dir1]

spectra> bucket.getSize()
===> 8
<img width="255" alt="screen shot 2018-04-25 at 9 34 02 pm" src="https://user-images.githubusercontent.com/7997157/39271249-6a6975e0-48d0-11e8-941f-582b853142d4.png">

**Comment by gtrossell** [comment]
Thanks @rpmoore, if you can implement that, that would be amazing. Currently even if you pass the / it doesn't work at the moment.

**Comment by sage-t** [comment]
`bucket.getBulk('dir1/', "./")` (or `bucket.getBulk(['dir1/'], "./")`) will now get the entire directory tree under dir1/
