### ISSUE TITLE
Switch option to overwrite existing script

### ISSUE THREAD

**Issue by gtrossell** [SpectraLogic/ds3_script#36]
Option to overwrite scripts

When recording scripts, can we please add the switch to overwrite a script with the same name. So that if you make a mistake you can just simply re-record the script, using the same name as before without having to exit, delete the broken script and then re-record.

**Comment by sage-t** [comment]
You can delete a script from bpsh using `:e -d <script>` but I will also add a re-record option.

**Comment by sage-t** [comment]
`:r -o <script>` will now overwrite the previous script 👍
