### ISSUE TITLE
Script output to Logfile

### ISSUE THREAD

**Issue by gtrossell** [SpectraLogic/ds3_script#38]
When a user runs a pre-made script it would nice to have the ablity to pipe the output of that script to a log or txt file so that if the script runs overnight or on a routine basis that they can read the log file to make sure the script ran successfully.

**Comment by sage-t** [comment]
The command `bpsh -l ./ script.groovy` should log to `./spectra.log`, but I noticed that it's not working properly so I'll work on it

**Comment by sage-t** [comment]
Now the `bpsh -l ./ script.groovy` will log the script's output and any error that occurs as well as print it out to the user's command line. Adding a `-d` flag will add a stack trace for any errors. If you only want to pipe the output to a specific file you can also do a redirect like `bpsh -l ./ script.groovy > output.txt`.
