### ISSUE TITLE
latest build fails 

### ISSUE THREAD

**Issue by gtrossell** [SpectraLogic/ds3_script#43]
Hello, 

While doing a clean build on Ubuntu 18.04 the build fails 

Attached is the --debug output 

[buildError.txt](https://github.com/SpectraLogic/ds3_script/files/2085950/buildError.txt)

**Comment by rpmoore** [comment]
Please rerun and include the non debug output.  As far as I can tell from the debug output, it worked, but there is so much noise that I can't be sure.

**Comment by gtrossell** [comment]
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileGroovy 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/ubuntu/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.0/6ceabf8e7f329b457c99f734b62cf80629796086/groovy-2.5.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Unable to load class groovy.xml.jaxb.JaxbGroovyMethods due to missing dependency javax/xml/bind/JAXBContext

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
1 actionable task: 1 executed

**Comment by gtrossell** [comment]
removed and reinstalled Gradle, now works.

**Comment by sage-t** [comment]
I'm guessing you are using Java 9 or 10? We fixed the javax/xml dependency for those versions but you might still be seeing warnings which is a problem with Groovy. Shouldn't affect the usability, though.

**Comment by gtrossell** [comment]
I was using Java-8 but for some reason Gradle was having issues. Just removing and re-downloading fixed the issue
