### ISSUE TITLE
Issue with bucket.object

### ISSUE THREAD

**Issue by gtrossell** [SpectraLogic/ds3_script#48]
spectra> bucket = client.getBucket('Bluechip_1')
===> name: Bluechip_1, client: {endpoint: 10.210.3.110, access_key: Z2Vvcmdl}
spectra> object = bucket.object('ActifioOnVaultv2/9/13208993/13208993/Image13208993/1/cloudbacker-done')
===> groovy.lang.MissingMethodException: No signature of method: com.spectralogic.dsl.models.BpBucket.object() is applicable for argument types: (java.lang.String) values: [ActifioOnVaultv2/9/13208993/13208993/Image13208993/1/cloudbacker-done]
Possible solutions: inject(groovy.lang.Closure), collect(), getObject(java.lang.String), collect(groovy.lang.Closure), inject(java.lang.Object, groovy.lang.Closure), inspect()

**Comment by sage-t** [comment]
Sorry, looks like the documentation wasn't updated. `bucket.object()` should be `bucket.getObject()`
